export const commonMessage = {
  error:
    "Something went wrong, if this keeps happening email alex@sprouttechlab.com",
  deleteSuccess: "Deleted successfully",
  saveSuccess: "Save Successfully",
  updateSuccess: "Update Successfully",
  updateFail: "Update failed",
  createSuccess: "Create Successfully",
  removeSuccess: "Remove successfully",
  loginFail: "Login failed",
  unsubscribeSuccess: "Unsubscribed successfully",
  subscribeSuccess: "Subscribed successfully",
  addMemberSuccess: "Add member successfully",
  createMemberSuccess: "Create member successfully",
  failGetData: "Failed to get data",
  addAttributeSuccess: "Add attribute successfully",
  addAttributeFail: "Add attribute failed",
  requireFillAll: "Please fill in all required fields",
  uploadOnlyImage: "You can only upload image file!",
  uploadMaximumImageSize: "File size should be less than 300MB",
  uploadImageFail: "Upload image failed. Please try again.",
  updatePasswordSuccess: "Update password successfully",
  updateProfileSuccess: "Update profile successfully",
  subscriptionIdNotFound: "Subscription ID not found",
  cannotUnsubscribe: "Cannot unsubscribe this product",
  failToFetch: "TypeError: Failed to fetch",
  inputOrderItems: "Please input all fields of order items!",
  requiredOrderItem: "Order items must be greater than 0",
  pleaseSelectProduct: "Please select product to update",
};

export const formMessage = {
  name: "Please input your name!",
  shopifyShopId: "Please input your shopify id!",
  shopifyAccessToken: "Please input your shopify access token!",
  vaildEmail: "Please input a valid email!",
  email: "Please input your email!",
  phoneNumber: "Please input your phone number!",
  website: "Please input your website!",
  vendorName: "Please input your vendor name!",
  selectVendorName: "Please select your vendor!",
  selectBrandName: "Please select your brand!",
  brandName: "Please input your brand name!",
  country: "Please input the country name!",
  city: "Please input the city name!",
  state: "Please input the state name!",
  zipCode: "Please input the zip code!",
  address: "Please input the address!",
  tooltipRequired: "This is a required field",
  tooltipOptional: "This is a optional field",
  defaultValue: "Please input the default value!",
  password: "Please input your password!",
  productName: "Please input the product name!",
  vendorPrice: "Please input the vendor price!",
  price: "Please input the product price!",
  style: "Please input the product style!",
  type: "Please input the product type!",
  currentPassword: "Please input your current password!",
  newPassword: "Please input your new password!",
  passwordLength: "Password must be at least 6 characters!",
  confirmPassword: "Please input confirm password!",
  passwordNotMatch: "The new password and confirm password do not match!",
  selectUser: "Please select the user!",
  description: "Please input the description!",
  sku: "Please input the sku!",
  color: "Please input the color!",
  size: "Please input the size!",
  quantity: "Please input the quantity!",
  orderItems: "Please input all fields of order items!",
  minimumQuantity: "Quantity must be greater than 0",
};
